#!/usr/bin/env bash
# This script changes the IP address of a machine
file=~/hosts.new
cp /etc/hosts $file

sed -i -e "$a\\n127.0.0.2\t127.0.0.1" $file
sed -i -e "$a\\n8.8.8.8\tfacebook.com\n" $file

cp -f $file /etc/hosts
